name: real-time-auction-system
services:
  server: &server-base
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      # - ./server:/app
      - /app/node_modules
    develop:
      watch:
        - path: ./server/package.json
          action: rebuild
        - path: ./server
          target: /app
          action: sync
    env_file: ./server/.env
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      REDIS_CACHE_URL: redis://redis-cache:6379
      REDIS_QUEUE_URL: redis://redis-queue:6379
    command: npm run start:dev
    depends_on:
      db:
        condition: service_healthy
      redis-cache:
        condition: service_started
      redis-queue:
        condition: service_started

  server-internal:
    <<: *server-base
    ports: []
    deploy:
      replicas: 2

  load-balancer:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server-internal

  db:
    image: postgres:16-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis-cache:
    image: redis:7.4-alpine
    command: redis-server --maxmemory 128mb --maxmemory-policy volatile-lru
    ports:
      - "${REDIS_CACHE_PORT}:6379"
    # volumes:
    #   - redis_cache_data:/data

  redis-queue:
    image: redis:7.4-alpine
    command: redis-server --appendonly yes
    ports:
      - "${REDIS_QUEUE_PORT}:6379"
    volumes:
      - redis_queue_data:/data

  redis-insight:
    image: redis/redisinsight:latest
    ports:
      - "${REDIS_INSIGHT_PORT}:5540"

  k6:
    image: grafana/k6:latest
    profiles: [ "load" ]
    volumes:
      - ./load:/scripts
    environment:
      BASE_URL: http://server:3000
    depends_on:
      server:
        condition: service_started

volumes:
  # redis_cache_data:
  postgres_data:
  redis_queue_data:
